### ISSUE TITLE
The source code for version 1.2.1 is missing

### ISSUE THREAD

**Issue by fubar-coder** [SharpTools/SharpCache#1]
It seems that this repository is out of date. Can you please either update this repository or change the NuGet package to point to the correct repository? Thanks in advance.

**Comment by andrecarlucci** [comment]
Hi Mark,

I guess when I pushed the new code (project.json structure) I did some mess merging the commit.
The new code is under the "src" folder: https://github.com/SharpTools/SharpCache/blob/master/src/SharpCache/MemCache.cs

I will delete the old code as soon as I get home.

Thanks for the heads up and if you could provide some feedback about using it I would really appreciate it :)

**Comment by fubar-coder** [comment]
I missed this, sorry. Thank you for the fast response.

**Comment by andrecarlucci** [comment]
There you go, I removed the old code :)
